version: "3.8"
services:
  todos:
    container_name: todos
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    build:
      context: ./
    ports:
      - 1337:1337

  caddy:
    image: caddy/caddy:2.5.2-alpine
    container_name: caddy-service
    restart: unless-stopped
    port:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config

  volumes:
    caddy_data:
    caddy_config:
